name: Run experiment 2
description: 'Run Gradle Experiment 2'

inputs:
  repositoryUrl:
    description: Project repository URL
    required: true
  branch:
    description: Git Branch
    required: true
  task:
    description: Gradle task
    required: true
  gradleEnterpriseUrl:
    description: Gradle Enterprise URL
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Gradle Experiment 2
      run: |
        cd gradle-enterprise-gradle-build-validation
        ./02-validate-local-build-caching-same-location.sh -r ${{ inputs.repositoryUrl }} -b ${{ inputs.branch }} -t ${{ inputs.task }} -s ${{ inputs.gradleEnterpriseUrl }}
      shell: bash
