/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform("com.squareup.okhttp3:okhttp-bom:4.9.0"))
    implementation("com.squareup.okhttp3:okhttp")
    implementation("com.squareup.okhttp3:okhttp-sse")

    implementation(platform("com.fasterxml.jackson:jackson-bom:2.12.3"))
    implementation("com.fasterxml.jackson.core:jackson-databind")

    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("info.picocli:picocli:4.6.1")
    annotationProcessor("info.picocli:picocli-codegen:4.6.1")
}

group = "com.gradle"
version = "1.0.0-SNAPSHOT"
description = "Application to fetch build scan data using the Gradle Enterprise Export API"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

tasks.compileJava {
    options.compilerArgs.add("-Aproject=${project.group}/${project.name}")
}

application {
    mainClass.set("com.gradle.enterprise.FetchBuildValidationData")
}
