package com.gradle.enterprise.api.client;

import java.net.MalformedURLException;
import java.net.URL;

public class ApiClientException extends RuntimeException {
    public ApiClientException() {
    }

    public ApiClientException(String message) {
        super(message);
    }

    public ApiClientException(String message, Throwable cause) {
        super(message, cause);
    }

    public ApiClientException(Throwable cause) {
        super(cause);
    }

    public ApiClientException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }

    protected static final URL buildScanUrl(URL gradleEnterpriseServerUrl, String buildScanId) {
        try {
            return new URL(gradleEnterpriseServerUrl, "/s/" + buildScanId);
        } catch (MalformedURLException e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }

    public static ApiClientException connectionFailed(URL gradleEnterpriseServer, String buildScanId, Throwable cause) {
        final String message = String.format("Unable to connect to %s in order to fetch build scan %s: %s", gradleEnterpriseServer, buildScanId, cause.getMessage());
        return new ApiClientException(message, cause);
    }

    public static ApiClientException unknownBuildAgent(URL gradleEnterpriseServer, String buildScanId, String buildAgent) {
        final String message = String.format("Build scan %s was generated by an unknown build agent: %s.", buildScanUrl(gradleEnterpriseServer, buildScanId), buildAgent);
        return new ApiClientException(message);
    }

    public static ApiClientException malformedEnvironmentVariable() {
        final String message = "Environment variable " + AuthenticationConfigurator.EnvVars.ACCESS_KEY + " is malformed (expected format: 'server-host=access-key' or 'server-host1=access-key1;server-host2=access-key2')";
        return new ApiClientException(message);
    }
}
