package com.gradle.enterprise.api.client;

public class ApiClientException extends RuntimeException {

    public ApiClientException(String message) {
        super(message);
    }

    public ApiClientException(String message, Throwable cause) {
        super(message, cause);
    }

    public static ApiClientException unknownBuildAgent(BuildScanUrl buildScanUrl, String buildAgent) {
        final String message = String.format("Build scan %s was generated by an unknown build agent: %s.", buildScanUrl, buildAgent);
        return new ApiClientException(message);
    }
}
