/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.codehaus.groovy:groovy:3.0.7")
    annotationProcessor("org.eclipse.sisu:org.eclipse.sisu.inject:0.3.4")
    compileOnly("org.apache.maven:maven-core:3.8.1")
    compileOnly("org.codehaus.plexus:plexus-component-annotations:1.7.1")
    compileOnly("com.gradle:gradle-enterprise-maven-extension:1.9")
}

group = "com.gradle"
version = "1.0.0-SNAPSHOT"
description = "Gradle Enterprise Capture Published Build Scan Maven Extension"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
