name: Run configuration cache experiment
description: "Runs the experiment to validate compatibility with the Gradle Configuration Cache"

inputs:
  tasks:
    description: "The Gradle tasks to invoke"
    required: false
  args:
    description: "Additional arguments to pass to Gradle"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: true
    - name: Run experiment
      id: run
      run: |
        # Need to run both builds within same job id to avoid calculating task graph as
        # configuration cache cannot be reused when environment variable 'GITHUB_ACTION' has changed
        ./gradlew --configuration-cache ${{ inputs.tasks }} ${{ inputs.args }} 2>&1 | tee -a /tmp/run-1.log
        echo "configCacheStored=$(grep "Configuration cache entry stored" /tmp/run-1.log | wc -l)" >> $GITHUB_OUTPUT
        ./gradlew --configuration-cache ${{ inputs.tasks }} ${{ inputs.args }} 2>&1 | tee -a /tmp/run-2.log
        echo "configCacheReused=$(grep "Configuration cache entry reused" /tmp/run-2.log | wc -l)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Validate Gradle Configuration Cache compatibility
      run: exit 3
      if: steps.run.outputs.configCacheReused == '0' || steps.run.outputs.configCacheStored != steps.run.outputs.configCacheReused
      shell: bash
