#!/usr/bin/env bash

# ARG_OPTIONAL_SINGLE([access-key],[A],[])
# ARG_OPTIONAL_SINGLE([username],[U],[],[])
# ARG_OPTIONAL_SINGLE([password],[P],[])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
### END OF CODE GENERATED BY Argbash (sortof) ### ])

