name: Run experiment 2
description: "Runs experiment 2 of the build validation scripts for Gradle"

inputs:
  gitRepo:
    description: "The URL for the Git repository to validate"
    required: true
  gitBranch:
    description: "The branch for the Git repository to validate"
    required: false
  gitCommitId:
    description: "The Git commit id for the Git repository to validate"
    required: false
  projectDir:
    description: "The build invocation directory within the Git repository"
    required: false
  tasks:
    description: "The Gradle tasks to invoke"
    required: false
  args:
    description: "Additional arguments to pass to Gradle"
    required: false
  gradleEnterpriseUrl:
    description: "The URL for the Gradle Enterprise server to connect to"
    required: false
  enableGradleEnterprise:
    description: "Enables Gradle Enterprise on a project not already connected"
    required: false
outputs:
  buildScanFirstBuild:
    description: "First build scan url"
    value: ${{ steps.run.outputs.buildScanFirstBuild }}
  buildScanSecondBuild:
    description: "Second build scan url"
    value: ${{ steps.run.outputs.buildScanSecondBuild }}

runs:
  using: "composite"
  steps:
    - name: Run Gradle Experiment 2
      id: run
      run: |
        cd gradle-enterprise-gradle-build-validation

        # Need to process separately tasks argument as it may contain whitespaces
        ARG_TASKS=""
        if [ ! -z "${{ inputs.tasks }}" ]; then
          ARG_TASKS="-t ${{inputs.tasks }}"
        fi

        # Unprotected arguments
        UNPROTECTED_ARGS="-r ${{ inputs.gitRepo }}"
        if [ ! -z "${{ inputs.gitBranch }}" ]; then
          UNPROTECTED_ARGS="$UNPROTECTED_ARGS -b ${{ inputs.gitBranch }}"
        fi
        if [ ! -z "${{ inputs.gitCommitId }}" ]; then
          UNPROTECTED_ARGS="$UNPROTECTED_ARGS -c ${{ inputs.gitCommitId }}"
        fi
        ARG_ARGS="${{ inputs.args }}"
        if [ ! -z "${{ inputs.args }}" ]; then
          UNPROTECTED_ARGS="$UNPROTECTED_ARGS -a ${{ inputs.args }}"
        fi
        if [ ! -z "${{ inputs.projectDir }}" ]; then
          UNPROTECTED_ARGS="$UNPROTECTED_ARGS -p ${{ inputs.projectDir }}"
        fi
        if [ ! -z "${{ inputs.gradleEnterpriseUrl }}" ]; then
          UNPROTECTED_ARGS="$UNPROTECTED_ARGS -s ${{ inputs.gradleEnterpriseUrl }}"
        fi
        if [ ! -z "${{ inputs.enableGradleEnterprise }}" ]; then
          UNPROTECTED_ARGS="$UNPROTECTED_ARGS -e"
        fi

        # run experiment
        ./02-validate-local-build-caching-same-location.sh "${ARG_TASKS}" ${UNPROTECTED_ARGS}

        # set scans url as output
        RECEIPT_FILE=".data/02-validate-local-build-caching-same-location/latest/exp2-*.receipt"
        echo "::set-output name=buildScanFirstBuild::$(grep "first build" ${RECEIPT_FILE} | sed 's/.* //')"
        echo "::set-output name=buildScanSecondBuild::$(grep "second build" ${RECEIPT_FILE} | sed 's/.* //')"
      shell: bash
